[LidDrivenCavity]
Re = 500.0              # Reynolds number
length = 1.0            # Length of Grid
grid_points = 100       # Number Of GridPoints
time_step = 0.01        # Time step
max_iterations = 10000     # Maximum Number of iterations
tolerance = 1e-6        # tolerance adjust
python_plot = true
lid_velocity = 1.0