name: Build LidDrivenCavity

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            ninja-build \
            meson \
            g++ \
            libsfml-dev \
            libomp-dev \
            python3

      - name: Setup Meson build dir
        run: |
          meson setup build

      - name: Compile project
        run: |
          meson compile -C build